/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as LogisticsIndexRouteImport } from './routes/logistics.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CarouselsIndexRouteImport } from './routes/carousels.index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as CategoriesNewRouteImport } from './routes/categories.new'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories.$categoryId'
import { Route as CarouselsNewRouteImport } from './routes/carousels.new'
import { Route as CarouselsCarouselIdRouteImport } from './routes/carousels.$carouselId'
import { Route as BrandsNewRouteImport } from './routes/brands.new'
import { Route as BrandsBrandIdRouteImport } from './routes/brands.$brandId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsIndexRoute = LogisticsIndexRouteImport.update({
  id: '/logistics/',
  path: '/logistics/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarouselsIndexRoute = CarouselsIndexRouteImport.update({
  id: '/carousels/',
  path: '/carousels/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewRoute = CategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarouselsNewRoute = CarouselsNewRouteImport.update({
  id: '/carousels/new',
  path: '/carousels/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CarouselsCarouselIdRoute = CarouselsCarouselIdRouteImport.update({
  id: '/carousels/$carouselId',
  path: '/carousels/$carouselId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsNewRoute = BrandsNewRouteImport.update({
  id: '/brands/new',
  path: '/brands/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/new': typeof BrandsNewRoute
  '/carousels/$carouselId': typeof CarouselsCarouselIdRoute
  '/carousels/new': typeof CarouselsNewRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/new': typeof CategoriesNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/brands/': typeof BrandsIndexRoute
  '/carousels/': typeof CarouselsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/new': typeof BrandsNewRoute
  '/carousels/$carouselId': typeof CarouselsCarouselIdRoute
  '/carousels/new': typeof CarouselsNewRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/new': typeof CategoriesNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/brands': typeof BrandsIndexRoute
  '/carousels': typeof CarouselsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/logistics': typeof LogisticsIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/new': typeof BrandsNewRoute
  '/carousels/$carouselId': typeof CarouselsCarouselIdRoute
  '/carousels/new': typeof CarouselsNewRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/new': typeof CategoriesNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/brands/': typeof BrandsIndexRoute
  '/carousels/': typeof CarouselsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/brands/$brandId'
    | '/brands/new'
    | '/carousels/$carouselId'
    | '/carousels/new'
    | '/categories/$categoryId'
    | '/categories/new'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/new'
    | '/brands/'
    | '/carousels/'
    | '/categories/'
    | '/logistics/'
    | '/notifications/'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/brands/$brandId'
    | '/brands/new'
    | '/carousels/$carouselId'
    | '/carousels/new'
    | '/categories/$categoryId'
    | '/categories/new'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/new'
    | '/brands'
    | '/carousels'
    | '/categories'
    | '/logistics'
    | '/notifications'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/brands/$brandId'
    | '/brands/new'
    | '/carousels/$carouselId'
    | '/carousels/new'
    | '/categories/$categoryId'
    | '/categories/new'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/new'
    | '/brands/'
    | '/carousels/'
    | '/categories/'
    | '/logistics/'
    | '/notifications/'
    | '/orders/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  BrandsNewRoute: typeof BrandsNewRoute
  CarouselsCarouselIdRoute: typeof CarouselsCarouselIdRoute
  CarouselsNewRoute: typeof CarouselsNewRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CategoriesNewRoute: typeof CategoriesNewRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CarouselsIndexRoute: typeof CarouselsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  LogisticsIndexRoute: typeof LogisticsIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/': {
      id: '/logistics/'
      path: '/logistics'
      fullPath: '/logistics/'
      preLoaderRoute: typeof LogisticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carousels/': {
      id: '/carousels/'
      path: '/carousels'
      fullPath: '/carousels/'
      preLoaderRoute: typeof CarouselsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/new': {
      id: '/categories/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof CategoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carousels/new': {
      id: '/carousels/new'
      path: '/carousels/new'
      fullPath: '/carousels/new'
      preLoaderRoute: typeof CarouselsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carousels/$carouselId': {
      id: '/carousels/$carouselId'
      path: '/carousels/$carouselId'
      fullPath: '/carousels/$carouselId'
      preLoaderRoute: typeof CarouselsCarouselIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/new': {
      id: '/brands/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof BrandsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  BrandsNewRoute: BrandsNewRoute,
  CarouselsCarouselIdRoute: CarouselsCarouselIdRoute,
  CarouselsNewRoute: CarouselsNewRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CategoriesNewRoute: CategoriesNewRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CarouselsIndexRoute: CarouselsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  LogisticsIndexRoute: LogisticsIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
